package com.company.swingUI.JPanels;

import com.company.inter.Record;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.company.swingUI.Config;
import javax.swing.JOptionPane;

/**
 *
 * @author islam
 */
public class JPanelHistory extends javax.swing.JPanel {

    /**
     * Creates new form JPanelHistory
     */
    public JPanelHistory() {
        initComponents();
        configureTable();
    }

    private void configureTable(){
        System.out.println("Hi");
        jTableHistory.setModel(new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }            
        });
    }
    
    public <T extends Record> void showHistory(List<T> Records){
        if(Records.isEmpty()){
            jTableHistory.removeAll();
            JOptionPane.showMessageDialog(this, "There is no record within dates.");
            return;
        };
        this.jTableHistory.setModel(new DefaultTableModel(((Record)Records.get(0)).getColumnNames(), 0));
        jTableHistory.getColumnModel().getColumn(Config.DATA_COL).setMaxWidth(0);
        jTableHistory.getColumnModel().getColumn(Config.N_COL).setMaxWidth(50);
        
        int row = 0;
        for(T r : Records){
            ((DefaultTableModel)this.jTableHistory.getModel()).addRow(r.toTableRow(row++));
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistory = new javax.swing.JTable();

        jTableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Sales"
            }
        ));
        jScrollPane1.setViewportView(jTableHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHistory;
    // End of variables declaration//GEN-END:variables
}
