package com.company.swingUI.JPanels;

import com.company.bean.Product;
import com.company.bean.SaleRecord;
import com.company.dataAccess.implementation.SaleDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author islam
 */
public class JPanelSell extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSell
     */
    public JPanelSell() {
        initComponents();
        testData();
        configureTable();
    }

    private void configureTable() {
        jTableSell.setRowHeight(25);
        jTableSell.getColumnModel().getColumn(1).setCellEditor(new ProductCellEditor(new EventCellInputChange() {
            @Override
            public void inputChanged() {
                DefaultTableModel model = (DefaultTableModel) jTableSell.getModel();
                if (model.getValueAt(model.getRowCount() - 1, 0) != null) {
                    model.addRow(new Object[model.getColumnCount()]);
                }
                sumAndShow();
                System.out.println("Input Change Fired");
            }
        }));
    }

    private void testData() {
        jTableSell.getColumnModel().getColumn(4).setCellEditor(new QtyCellEditor(new EventCellInputChange() {
            @Override
            public void inputChanged() {
                sumAndShow();
            }
        }));

//        DefaultTableModel model = (DefaultTableModel) jTableSell.getModel();
//        model.addRow(new Product("Coca", "cda", 2.0, -1, "A1", 2).toTableRow(jTableSell.getRowCount() + 1));
//        model.addRow(new Product("Cofasca", "csa", 3.0, -1, "A2", 2).toTableRow(jTableSell.getRowCount() + 1));
//        model.addRow(new Product("Cocfaa", "cvf", 4.0, -1, "A3", 2).toTableRow(jTableSell.getRowCount() + 1));
//        model.addRow(new Product("Cofaca", "ccd", 5.0, -1, "A4", 2).toTableRow(jTableSell.getRowCount() + 1));
//        model.addRow(new Product("Cocfasa", "cas", 6.0, -1, "A5", 2).toTableRow(jTableSell.getRowCount() + 1));
    }

    public double sumAndShow() {
        double sum = 0;
        for (int row = 0; row < jTableSell.getRowCount() - 1; row++) {
            sum += (double) jTableSell.getValueAt(row, 6);
        }
        totalJLabel.setText("Total: " + String.format("%.2f", sum));
        return sum;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSell = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSell = new javax.swing.JTable();
        simpleJLabel = new javax.swing.JLabel();
        totalJLabel = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();

        jButtonSell.setText("Process Sell");
        jButtonSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellActionPerformed(evt);
            }
        });

        jTableSell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Part_Name", "Part_Number", "Part_Description", "Part_Quantity", "Part_Price", "Total_Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSell.setToolTipText("");
        jTableSell.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableSell);
        if (jTableSell.getColumnModel().getColumnCount() > 0) {
            jTableSell.getColumnModel().getColumn(0).setResizable(false);
            jTableSell.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTableSell.getColumnModel().getColumn(1).setPreferredWidth(160);
        }

        simpleJLabel.setText("Enter Product Code");

        totalJLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalJLabel.setText("Total: 0");

        jTextFieldSearch.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpleJLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSell, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simpleJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSell, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellActionPerformed
        jTableSell.clearSelection();
        DefaultTableModel model = (DefaultTableModel) jTableSell.getModel();
        List<SaleRecord> sr = this.modelToRecord(model);
        if (sr == null) {
            JOptionPane.showMessageDialog(this, "Quantity cant be 0.");
            return;
        } else if (sr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nothing to sell.");
            return;
        }
        
        SaleDAO sdao = new SaleDAO();
        int affectedRows = sdao.sellProducts(sr);
        if(affectedRows==0){
            System.out.println("Nothing inserted to db, something might gone wrong!");
        }
        model.setRowCount(0);
    }//GEN-LAST:event_jButtonSellActionPerformed

    private List<SaleRecord> modelToRecord(DefaultTableModel model) {
        List<SaleRecord> sr = new ArrayList<>();
        for (int row = 0; row < model.getRowCount() - 1; row++) {
            if (((int) model.getValueAt(row, 4)) <= 0) {
                System.out.println("There is 0");
                return null;
            }

            sr.add(new SaleRecord(((Product) model.getValueAt(row, 0)).getId(),
                    (int) model.getValueAt(row, 4),
                    (double) model.getValueAt(row, 5)));
            //System.out.println(model.getDataVector().get(row));

        }
        return sr;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSell;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSell;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JLabel simpleJLabel;
    private javax.swing.JLabel totalJLabel;
    // End of variables declaration//GEN-END:variables
}
