package com.company.swingUI.JPanels;

import com.company.swingUI.Config;

/**
 *
 * @author islam
 */
public class TopButtonBarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TopButtonBarJPanel
     */
    
    public TopButtonBarJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sellJButton = new javax.swing.JButton();
        browseJButton = new javax.swing.JButton();
        addJButton1 = new javax.swing.JButton();

        sellJButton.setText("Sell");
        sellJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellJButtonActionPerformed(evt);
            }
        });

        browseJButton.setText("Browse");
        browseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseJButtonActionPerformed(evt);
            }
        });

        addJButton1.setText("Add");
        addJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sellJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addJButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseJButton)
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(sellJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(addJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sellJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellJButtonActionPerformed
        System.out.println("Sell Button Clicked");

        if (!Config.sellFrame.isVisible()) {
            Config.sellFrame.setVisible(true);
            Config.addFrame.setVisible(false);
            Config.browseFrame.setVisible(false);
        } else {
            Config.sellFrame.setVisible(false);
            
        }
    }//GEN-LAST:event_sellJButtonActionPerformed

    private void browseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseJButtonActionPerformed
        if (!Config.browseFrame.isVisible()) {
            Config.browseFrame.setVisible(true);
            Config.addFrame.setVisible(false);
            Config.sellFrame.setVisible(false);
        } else {
            Config.browseFrame.setVisible(false);
            
        }
    }//GEN-LAST:event_browseJButtonActionPerformed

    private void addJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButton1ActionPerformed
        System.out.println("Add Button Clicked");

        if (!Config.addFrame.isVisible()) {
            Config.addFrame.setVisible(true);
            Config.sellFrame.setVisible(false);
            Config.browseFrame.setVisible(false);
        } else {
            Config.addFrame.setVisible(false);
            
        }
    }//GEN-LAST:event_addJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton1;
    private javax.swing.JButton browseJButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sellJButton;
    // End of variables declaration//GEN-END:variables
}
